/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package WebCam;


import Clases.GuardarLeerCamara;
import Ventanas.BuscarCliente;
import Ventanas.ClienteJuridicoP;
import Ventanas.ClienteNaturalP;
import Ventanas.EjecutivoP;
import Ventanas.EmpleadoP;
import Ventanas.ProductoP;
import Ventanas.ProveedorP;
import Ventanas.RepresentanteP;
import com.googlecode.javacv.FrameGrabber;
import com.googlecode.javacv.VideoInputFrameGrabber;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Reymundo Tenorio
 */
public class Dispositivos extends javax.swing.JDialog {

    /**
     * Creates new form Dispositivos
     * @param parent
     * @param modal
     */
    public Dispositivos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
           try{
        this.setIconImage (new ImageIcon(getClass().getResource("Dispositivos.png")).getImage());
        }catch(NullPointerException ex){}
        initComponents();
        
        String [] Devices = null;
        try {
            Devices = VideoInputFrameGrabber.getDeviceDescriptions();
        } catch (FrameGrabber.Exception ex) {
            JOptionPane.showMessageDialog(parent, "No Se Han Encontrado Cámaras Conectadas","Cámaras No Encontradas",JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
   
      for (String Dev : Devices) {
        cmbDevice.addItem(Dev);
      }

       GuardarLeerCamara GC = new GuardarLeerCamara();
    
      int cam = 0;
        try {
            cam = GC.DatoCamara();
        } catch (IOException ex) {
         //   Logger.getLogger(Dispositivos.class.getName()).log(Level.SEVERE, null, ex);
        }
      
      if((cmbDevice.getItemCount())>cam){
      cmbDevice.setSelectedIndex(cam);
      }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbDevice = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seleccionar Dispositivo de Captura");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dispositivos de Captura");
        jPanel1.add(jLabel1);

        cmbDevice.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDeviceItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbDevice);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        btnOK.setText("Aceptar");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        jPanel2.add(btnOK);

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancel);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        setSize(new java.awt.Dimension(600, 141));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private int Camara;
   
    private ProductoP Producto;
    private EjecutivoP Ejecutivo;
    private ProveedorP Proveedor;
    private EmpleadoP Empleado;
    private ClienteNaturalP Cliente;
    private ClienteJuridicoP ClienteJ;
    private RepresentanteP Representante;
   
    public void setBC(BuscarCliente BC) {
        this.BC = BC;
    }
    private BuscarCliente BC;

    public void setRepresentante(RepresentanteP Representante) {
        this.Representante = Representante;
    }

    public void setClienteJ(ClienteJuridicoP ClienteJ) {
        this.ClienteJ = ClienteJ;
    }

    public void setProducto(ProductoP Producto) {
        this.Producto = Producto;
    }

    public void setEjecutivo(EjecutivoP Ejecutivo) {
        this.Ejecutivo = Ejecutivo;
    }

    public void setProveedor(ProveedorP Proveedor) {
        this.Proveedor = Proveedor;
    }

    public void setEmpleado(EmpleadoP Empleado) {
        this.Empleado = Empleado;
    }

    public void setCliente(ClienteNaturalP Cliente) {
        this.Cliente = Cliente;
    }

    
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

      this.setResizable(false);
      this.toFront();
   
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened
private boolean Flag = false;

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed

this.Flag = true;        
        
 this.Camara = cmbDevice.getSelectedIndex();
 WebCam WebCam = new WebCam(Camara);
 
 if(Representante!=null){         
         WebCam.setHome("Representante\\");
        }
 if(Cliente!=null){         
         WebCam.setHome("Cliente\\");
        }
 if(BC!=null){         
         WebCam.setHome("Cliente\\");
        }
  if(ClienteJ!=null){         
         WebCam.setHome("ClienteJ\\");
        }
 if(Ejecutivo!=null){         
         WebCam.setHome("Ejecutivo\\");
        }
 if(Empleado!=null){         
         WebCam.setHome("Empleado\\");
        }
 if(Producto!=null){         
         WebCam.setHome("Producto\\");
        }
 if(Proveedor!=null){         
         WebCam.setHome("Proveedor\\");
        }
 
 WebCam.setCliente(Cliente);
 WebCam.setEjecutivo(Ejecutivo);
  WebCam.setBC(BC);
 WebCam.setEmpleado(Empleado);
 WebCam.setProducto(Producto);
 WebCam.setProveedor(Proveedor);
 WebCam.setClienteJ(ClienteJ);
 WebCam.setRepresentante(Representante);
 
 

 
 //WebCam.setDispositivos(this);
 WebCam.setVisible(true);

 
    
 this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_btnOKActionPerformed

    private void cmbDeviceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDeviceItemStateChanged
btnOK.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDeviceItemStateChanged

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
 
        if(Flag == false){
            
        if(Cliente!=null){         
        Cliente.setVisible(true);
        }
        if(BC!=null){         
        BC.setVisible(true);
        }
        if(Representante!=null){         
        Representante.setVisible(true);
        }
        if(ClienteJ!=null){         
        ClienteJ.setVisible(true);
        }
        if(Proveedor!=null){         
        Proveedor.setVisible(true);
        }
        if(Ejecutivo!=null){         
        Ejecutivo.setVisible(true);
        }
        if(Producto!=null){         
        Producto.setVisible(true);
        }
        if(Empleado!=null){         
        Empleado.setVisible(true);
        }
        
        }
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dispositivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Dispositivos dialog = null;
                dialog = new Dispositivos(new javax.swing.JFrame(), true);    
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox cmbDevice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
