package WebCam;



import Ventanas.BuscarCliente;
import Ventanas.ClienteJuridicoP;
import Ventanas.ClienteNaturalP;
import Ventanas.EjecutivoP;
import Ventanas.EmpleadoP;
import Ventanas.ProductoP;
import Ventanas.ProveedorP;
import Ventanas.RepresentanteP;
import java.awt.Frame;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Reymundo Tenorio
 */
public class ViewImageFrame extends javax.swing.JDialog {
private File Img=null;
private ImageIcon II=null;
private ImageIcon Imag=null;
private final String Ruta;
    /**
     * Creates new form ViewImageFrame
     * @param parent
     * @param modal
     * @param imagefile
     */
    public ViewImageFrame(Frame parent,boolean modal,String imagefile) {
        super(parent,modal);
        
        try{
        this.setIconImage (new ImageIcon(getClass().getResource("ViewImage.png")).getImage());
        }catch(NullPointerException ex){}
        initComponents();
        
        this.Ruta = imagefile;
        Img=new File(imagefile);
        setTitle("Imágen: "+Img.getName()+" - WebCam Capture Viewer");
        II=new ImageIcon(Img.getAbsolutePath());
        Imag = new ImageIcon(II.getImage().
                                      getScaledInstance(640,480,
                                                        Image.SCALE_DEFAULT));
        Imagen.setIcon(Imag);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ver Imágen");
        setResizable(false);

        Imagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Imagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImagenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Imagen, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Imagen, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private WebCam WebCam;

    private ProductoP Producto;
    private EjecutivoP Ejecutivo;
    private ProveedorP Proveedor;
    private EmpleadoP Empleado;
    private ClienteNaturalP Cliente;
    private ClienteJuridicoP ClienteJ;
    private RepresentanteP Representante;
   
    public void setBC(BuscarCliente BC) {
        this.BC = BC;
    }
    private BuscarCliente BC;

    public void setRepresentante(RepresentanteP Representante) {
        this.Representante = Representante;
    }

    public void setClienteJ(ClienteJuridicoP ClienteJ) {
        this.ClienteJ = ClienteJ;
    }

    public void setProducto(ProductoP Producto) {
        this.Producto = Producto;
    }

    public void setEjecutivo(EjecutivoP Ejecutivo) {
        this.Ejecutivo = Ejecutivo;
    }

    public void setProveedor(ProveedorP Proveedor) {
        this.Proveedor = Proveedor;
    }

    public void setEmpleado(EmpleadoP Empleado) {
        this.Empleado = Empleado;
    }

    public void setCliente(ClienteNaturalP Cliente) {
        this.Cliente = Cliente;
    }       

    public void setWebCam(WebCam WebCam) {
        this.WebCam = WebCam;
    }
   

    private void ImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenMouseClicked
 if(evt.getClickCount()==2){
              
     
        //System.out.println("Ruta "+Ruta);
    
     if(Cliente!=null){
              Cliente.Foto(Ruta);
              Cliente.setFoto();
              this.WebCam.Cerrar();
     }
     
     if(BC!=null){
              BC.Foto(Ruta);
              BC.setFoto();
              this.WebCam.Cerrar();
     }
     
     if(Representante!=null){
              Representante.Foto(Ruta);
              Representante.setFoto();
              this.WebCam.Cerrar();
     }
     if(ClienteJ!=null){
              ClienteJ.Foto(Ruta);
              ClienteJ.setFoto();
              this.WebCam.Cerrar();
     }
     if(Proveedor!=null){
              Proveedor.Foto(Ruta);
              Proveedor.setFoto();
              this.WebCam.Cerrar();
     }
     if(Ejecutivo!=null){
              Ejecutivo.Foto(Ruta);
              Ejecutivo.setFoto();
              this.WebCam.Cerrar();
     }
     if(Producto!=null){
              Producto.Foto(Ruta);
              Producto.setFoto();
              this.WebCam.Cerrar();
     }
     if(Empleado!=null){
              Empleado.Foto(Ruta);
              Empleado.setFoto();
              this.WebCam.Cerrar();
     }
       
              
              this.dispose();
              
 }
               // TODO add your handling code here:
    }//GEN-LAST:event_ImagenMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagen;
    // End of variables declaration//GEN-END:variables
}
