/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.CustomTextField;
import Procedimientos.Conexion;
import java.awt.Color;
import java.io.IOException;
import java.net.Socket;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
 
/**
 *
 * @author ReymundoAsus
 */
public class ContrasenaOlvidada extends javax.swing.JDialog {

    /**
     * Creates new form FotoModo
     * @param parent
     * @param modal
     * @throws java.io.IOException
     */
    public ContrasenaOlvidada(java.awt.Frame parent, boolean modal) throws IOException {
        super(parent, modal);
              
        try {
            this.setIconImage(new ImageIcon(getClass().getResource("Icono.png")).getImage());
        } catch (NullPointerException ex) {
        }
         
        
        initComponents();
        
        Alert = new Alerta(1);
        Alert.setRecordarContra("Activado");
        
        this.setResizable(false);
     
        //Alert.setInicio(this);
    }

     Alerta Alert;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrinc = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Recuperar Contraseña");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        PanelPrinc.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingrese Su Nombre de Usuario");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Correo.png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setPreferredSize(new java.awt.Dimension(48, 80));

        CustomTextField customTextField = new CustomTextField(100);
        txtUser = customTextField;
        customTextField.setPlaceholder("Ingrese Su Nombre de Usuario");
        customTextField.setFont(new java.awt.Font("Tahoma", 0, 16));
        customTextField.setForeground(Color.BLACK);
        customTextField.setPlaceholderForeground(Color.LIGHT_GRAY);
        txtUser.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtUser.setToolTipText("Ingrese Su Nombre de Usuario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );

        PanelPrinc.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        jButton1.setMnemonic('A');
        jButton1.setText("Aceptar");
        jButton1.setToolTipText("Recuperar Constraseña");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setMnemonic('C');
        jButton2.setText("Cancelar");
        jButton2.setToolTipText("Cancelar/Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        PanelPrinc.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(PanelPrinc, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(491, 182));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    public void AgregarTexto (String Texto){
        
        
        jLabel1.setText(Texto);
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        
//        rdBusc.setSelected(true);        
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    
    ResultSet resultado;

class Enviar extends Thread{
ProcesandoInfo p;

public Enviar(ProcesandoInfo P){
this.p=P;
}
@Override
public void run(){
       
    try {
            Alert.Empezar(this.p);        // TODO add your handling code here:
        } catch (IOException | MessagingException ex) {

              }
}
}
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
      Conexion con = new Conexion();
        try {
            con.Conectar("SistemaFarmacia", "sa", "1234");
        } catch (SQLException | ClassNotFoundException | IOException | MessagingException ex) {
            Logger.getLogger(ContrasenaOlvidada.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      String NombreUsuario = txtUser.getText().trim();
        
      String Usuario = "reymundotenorio1";
      String Contrasena = "1234";
      String Correo = "dj-rex@hotmail.com";
      String Estado = "-";
      
      int ID = 0;
//      
//      try{
//          
//        resultado = Conexion.consulta("Select ID_Usuario, Nombre_Usuario, Contrasena_Usuario, Correo_Usuario,"
//                + " Estado_Usuario from UsuarioV where Nombre_Usuario = '"+NombreUsuario+"'");
//          
//        while(resultado.next()){
//            ID = resultado.getInt(1);
//            Usuario = resultado.getString(2);
//            Contrasena = resultado.getString(3);     
//            Estado = resultado.getString(4);
//        }
//      }catch(SQLException ex){}
//        
//      if(ID==0){
//          JOptionPane.showMessageDialog(this, "Usuario no existe", "No Existe", JOptionPane.ERROR_MESSAGE);
//          return;
//      }
//      
//      if("Inactivo".equals(Estado)){
//          JOptionPane.showMessageDialog(this, "Usuario no está disponible", "No disponible", JOptionPane.ERROR_MESSAGE);
//          return;
//      }
//        
      
      
      Alert.setUser(Usuario);
      Alert.setPass(Contrasena);
      Alert.setCorreo(Correo);
      
      Alert.setConOlv(this);
      
      
       int Pos = Correo.indexOf('@');
       String Sub = Correo.substring(0, Pos);
       
       String Gest = Correo.substring(Pos, Correo.length());
       
       int Tamano = Sub.length()-2;
       String SubEmail;
       
       if(Sub.length()>=2){   
           SubEmail = Sub.substring(0,2);    
       }else{
           SubEmail = Sub.substring(0,1);     
       }
       
       for(int i=0; i<Tamano; i++){       
        SubEmail = SubEmail.concat("*");
       }
       
       String Full = SubEmail.concat(Gest);
       
      int Eleccion = JOptionPane.showConfirmDialog(this,"Se le enviará su información a su correo electrónico "
              +Full,"Enviar información al correo "+Full, JOptionPane.YES_NO_OPTION);
        
      
        if(Eleccion == JOptionPane.YES_OPTION){
           
            
            String dirWeb = "www.google.com";
            int puerto = 80;
            Socket s = new Socket();
            
            try{
             s = new Socket(dirWeb, puerto);
//             if(s.isConnected()){
//           //  System.out.println("Conexión establecida con la dirección: " +  dirWeb + " a travéz del puerto: " + puerto);
//             }
             }catch(Exception e){
           //    System.err.println("No se pudo establecer conexión con: " + dirWeb + " a travez del puerto: " + puerto);

                JOptionPane.showMessageDialog(this,"No se pudo enviar los datos, revise su conexión de acceso a internet"
                   , "No enviado", JOptionPane.ERROR_MESSAGE);
                Alert.dispose();
                this.dispose(); 
            }
        
           if(s.isConnected()){
    
           this.setEnabled(false);
           ProcesandoInfo p=new ProcesandoInfo();
           p.setVisible(true);
           this.setVisible(false);
           p.toFront();
           new Enviar(p).start();
            
           }
        }
        else{
           JOptionPane.showMessageDialog(this, "Ha cancelado el envio de su información a su correo electrónico",
                   "Cancelado", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContrasenaOlvidada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContrasenaOlvidada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContrasenaOlvidada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContrasenaOlvidada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ContrasenaOlvidada dialog = null;
                try {
                    dialog = new ContrasenaOlvidada(new javax.swing.JFrame(), true);
                } catch (IOException ex) {
                    Logger.getLogger(ContrasenaOlvidada.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrinc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
