/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.CustomTextField;
import Procedimientos.Conexion;
import ServerSocket.Servidor;
import com.keffect.effects.animatedEffects.EntryBoucing;
import com.keffectpanel.KEffectPanel;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.io.File;
import java.net.UnknownHostException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Reymundo Tenorio
 */
public class FacturacionP extends javax.swing.JFrame {

    /**
     * Creates new form ProductoP
     * @throws java.net.UnknownHostException
     */
    public FacturacionP() throws UnknownHostException {

       try {
            this.setIconImage(new ImageIcon(getClass().getResource("Icono.png")).getImage());
        } catch (NullPointerException ex) {
        }
         

        initComponents();
        PanelVer.setVisible(false);
        Tabla1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        Tabla.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
     
        
        new ServidorInit(this).start();

        /*COPIAR PEGAR DESACTIVAR*/
//         JTextComponent.KeyBinding[] newBindings = {
////        new JTextComponent.KeyBinding(
////          KeyStroke.getKeyStroke(KeyEvent.VK_C, InputEvent.CTRL_MASK),
////          DefaultEditorKit.beepAction),
//        new JTextComponent.KeyBinding(
//          KeyStroke.getKeyStroke(KeyEvent.VK_V, InputEvent.CTRL_MASK),
//          DefaultEditorKit.beepAction),
////        new JTextComponent.KeyBinding(
////            KeyStroke.getKeyStroke(KeyEvent.VK_X, InputEvent.CTRL_MASK),
////            DefaultEditorKit.beepAction)
////      
//         };
//            
//    Keymap k = txtNombre.getKeymap();
//    JTextComponent.loadKeymap(k, newBindings, txtNombre.getActions());
//    
//        MultipleEffect effects = new MultipleEffect();
//				effects.addEffect(new ShadowFrame(20));
//				effects.addEffect(new Shadow(1000));
//				effects.addEffect(new SplitHorizontalFade(1000));
//				effects.addEffect(new SplitVerticalFade(2000));
//				effects.addEffect(new DarkenReverse(6000,50));
//                                
        // PanelEffect.setEffect(effects);                    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        JMnModificar = new javax.swing.JMenuItem();
        TabbedPane = new org.edisoncor.gui.tabbedPane.TabbedPaneHeader();
        PanelVerFact = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();
        jPanel19 = new javax.swing.JPanel();
        btnpagar = new javax.swing.JButton();
        btnshowall1 = new javax.swing.JButton();
        btncancel4 = new javax.swing.JButton();
        PanelVer = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbbusc = new javax.swing.JComboBox();
        txtbusc = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btnshowall = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        btncancel3 = new javax.swing.JButton();

        JMnModificar.setText("Modificar");
        JMnModificar.setToolTipText("Modificar");
        jPopupMenu1.add(JMnModificar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ordenes Pendientes");
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        TabbedPane.setPreferredSize(new java.awt.Dimension(200, 574));

        PanelVer = PanelEffect;
        PanelVerFact.setBackground(new java.awt.Color(0, 153, 204));
        PanelVerFact.setLayout(new javax.swing.BoxLayout(PanelVerFact, javax.swing.BoxLayout.LINE_AXIS));

        jPanel18.setBackground(new java.awt.Color(0, 153, 204));
        jPanel18.setLayout(new java.awt.BorderLayout());

        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tabla1.setToolTipText("Lista Registros");
        Tabla1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tabla1.getTableHeader().setReorderingAllowed(false);
        Tabla1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tabla1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Tabla1FocusLost(evt);
            }
        });
        Tabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Tabla1MousePressed(evt);
            }
        });
        jScrollPane7.setViewportView(Tabla1);

        jPanel18.add(jScrollPane7, java.awt.BorderLayout.CENTER);

        jPanel19.setBackground(new java.awt.Color(0, 102, 153));

        btnpagar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnpagar.setForeground(new java.awt.Color(255, 255, 255));
        btnpagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pagar.png"))); // NOI18N
        btnpagar.setMnemonic('m');
        btnpagar.setText("Pagar");
        btnpagar.setToolTipText("Pagar Orden");
        btnpagar.setContentAreaFilled(false);
        btnpagar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnpagar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnpagar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnpagarFocusGained(evt);
            }
        });
        btnpagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpagarActionPerformed(evt);
            }
        });
        jPanel19.add(btnpagar);

        btnshowall1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnshowall1.setForeground(new java.awt.Color(255, 255, 255));
        btnshowall1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TablaTodos.png"))); // NOI18N
        btnshowall1.setMnemonic('m');
        btnshowall1.setText("Actualizar");
        btnshowall1.setToolTipText("Mostrar Todos Los Registros");
        btnshowall1.setContentAreaFilled(false);
        btnshowall1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnshowall1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnshowall1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowall1ActionPerformed(evt);
            }
        });
        jPanel19.add(btnshowall1);

        btncancel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btncancel4.setForeground(new java.awt.Color(255, 255, 255));
        btncancel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar.png"))); // NOI18N
        btncancel4.setMnemonic('c');
        btncancel4.setText("Cancelar");
        btncancel4.setToolTipText("Cancelar / Salir");
        btncancel4.setContentAreaFilled(false);
        btncancel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncancel4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncancel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancel4ActionPerformed(evt);
            }
        });
        jPanel19.add(btncancel4);

        jPanel18.add(jPanel19, java.awt.BorderLayout.SOUTH);

        PanelVerFact.add(jPanel18);

        TabbedPane.addTab("Ver", PanelVerFact);

        //PanelVer = PanelEffect2;
        PanelVer.setBackground(new java.awt.Color(0, 153, 204));
        PanelVer.setLayout(new javax.swing.BoxLayout(PanelVer, javax.swing.BoxLayout.LINE_AXIS));

        jPanel15.setBackground(new java.awt.Color(0, 153, 204));
        jPanel15.setLayout(new java.awt.BorderLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel4.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar Por: ");

        cmbbusc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbbusc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No.", "Fecha Compra", "Proveedor", "Empleado", "Modo Compra", "Tiempo Para Pagar" }));
        cmbbusc.setToolTipText("Buscar Por:");

        txtbusc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtbusc.setToolTipText("Buscar");
        CustomTextField customTextField9 = new CustomTextField(100);
        txtbusc = customTextField9;
        customTextField9.setPlaceholder("Ingrese Información a Buscar");
        customTextField9.setFont(new java.awt.Font("Tahoma", 0, 16));
        customTextField9.setForeground(Color.BLACK);
        customTextField9.setPlaceholderForeground(Color.LIGHT_GRAY);
        txtbusc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscKeyReleased(evt);
            }
        });
        /*txtbusc = new AutoComplete.AutoCompletar();
        ((AutoCompletar)txtbusc).setDesplegable(new DesplegableJPopUPMenu(txtbusc));
        ModeloAutoCompletar modelo1 = new ModeloVendNames();
        ((AutoCompletar)txtbusc).setModelo(modelo1);
        ((AutoCompletar)txtbusc).getDesplegable().setForeground(new Color(102,153,255));
        ((AutoCompletar)txtbusc).addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscTyped(evt);
            }
        });
        ((AutoCompletar)txtbusc).setToolTipText("Ingresar Dato a Buscar");*/

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cmbbusc, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtbusc, javax.swing.GroupLayout.DEFAULT_SIZE, 972, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbbusc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbusc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel15.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tabla.setToolTipText("Lista Registros");
        Tabla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tabla.getTableHeader().setReorderingAllowed(false);
        Tabla.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TablaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TablaFocusLost(evt);
            }
        });
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TablaMousePressed(evt);
            }
        });
        jScrollPane5.setViewportView(Tabla);

        jPanel15.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(0, 102, 153));

        btnshowall.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnshowall.setForeground(new java.awt.Color(255, 255, 255));
        btnshowall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TablaTodos.png"))); // NOI18N
        btnshowall.setMnemonic('m');
        btnshowall.setText("Mostrar Todos");
        btnshowall.setToolTipText("Mostrar Todos Los Registros");
        btnshowall.setContentAreaFilled(false);
        btnshowall.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnshowall.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnshowall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowallActionPerformed(evt);
            }
        });
        jPanel5.add(btnshowall);

        btnprint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnprint.setForeground(new java.awt.Color(255, 255, 255));
        btnprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imprimir.png"))); // NOI18N
        btnprint.setMnemonic('i');
        btnprint.setText("Imprimir");
        btnprint.setToolTipText("Imprimir/Mostrar Reporte");
        btnprint.setContentAreaFilled(false);
        btnprint.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnprint.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });
        jPanel5.add(btnprint);

        btncancel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btncancel3.setForeground(new java.awt.Color(255, 255, 255));
        btncancel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar.png"))); // NOI18N
        btncancel3.setMnemonic('c');
        btncancel3.setText("Cancelar");
        btncancel3.setToolTipText("Cancelar / Salir");
        btncancel3.setContentAreaFilled(false);
        btncancel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncancel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncancel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancel3ActionPerformed(evt);
            }
        });
        jPanel5.add(btncancel3);

        jPanel15.add(jPanel5, java.awt.BorderLayout.SOUTH);

        PanelVer.add(jPanel15);

        TabbedPane.addTab("Ver", PanelVer);

        getContentPane().add(TabbedPane, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1308, 742));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
 class ServidorInit extends Thread{

     Servidor Server = new Servidor();

        public ServidorInit(FacturacionP F) {
            this.F = F;
        }

FacturacionP F;

@Override
public void run(){
       
    try {
        Server.setF(F);
        Server.IniciarServidor();
    } catch (UnknownHostException ex) {
        Logger.getLogger(FacturacionP.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    }
    
    double Dinero = 0;

    public void setDinero(double Dinero) {
        this.Dinero = Dinero;
    }

    KEffectPanel PanelEffect = new KEffectPanel();
    KEffectPanel PanelEffect2 = new KEffectPanel();

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//                this.panelColor = new JPanel();
//		this.panelColor.setBackground(Color.BLACK);
//		this.panelColor.setBorder(new LineBorder(new Color(0, 0, 0)));
//		this.panelColor.setBounds(133, 618, 43, 32);
//                
//     PanelEffect.setEffect(new SplitHorizontalFade (1000,panelColor.getBackground()));
//     PanelEffect.startEffect();

        PanelEffect.setEffect(new EntryBoucing(1000));
        PanelEffect.startEffect();

//Date now = new Date();
//
//DateFormat df =  DateFormat.getDateInstance();
//DateFormat df1 = DateFormat.getDateInstance(DateFormat.SHORT);
//DateFormat df2 = DateFormat.getDateInstance(DateFormat.MEDIUM);
//DateFormat df3 = DateFormat.getDateInstance(DateFormat.LONG);
//DateFormat df4 = DateFormat.getDateInstance(DateFormat.FULL);
//String s =  df.format(now);
//String s1 = df1.format(now);
//String s2 = df2.format(now);
//String s3 = df3.format(now);
//String s4 = df4.format(now);
//System.out.println("(Default) Hoy es:" + s);
//System.out.println("(SHORT)   Hoy es:" + s1);
//System.out.println("(MEDIUM)  Hoy es:" + s2);
//System.out.println("(LONG)    Hoy es:" + s3);
//System.out.println("(FULL)    Hoy es:" + s4);
        double Cambio = 0;
        int ID_Cambio = 0;
        String Empleado = "";

     
      
        ModeloOrdenes.setNumRows(0);

        TituloLista();

        ActualizarTabla();
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private MenuPrincipal MP;

    public void setMP(MenuPrincipal MP) {
        this.MP = MP;
    }

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        MP.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void btncancel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancel4ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btncancel4ActionPerformed

    private void btnshowall1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowall1ActionPerformed
        ActualizarTabla();       // TODO add your handling code here:
    }//GEN-LAST:event_btnshowall1ActionPerformed

    private void btnpagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpagarActionPerformed
        ActivarBotones();
        Pagar();
    }//GEN-LAST:event_btnpagarActionPerformed

    private void btnpagarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnpagarFocusGained
        ActivarBotones();        // TODO add your handling code here:
    }//GEN-LAST:event_btnpagarFocusGained

    private void Tabla1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tabla1MousePressed

    private void Tabla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla1MouseClicked
        if (evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1) {
            Pagar();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_Tabla1MouseClicked

    private void Tabla1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tabla1FocusLost
        ActivarBotones();      // TODO add your handling code here:
    }//GEN-LAST:event_Tabla1FocusLost

    private void Tabla1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tabla1FocusGained
        ActivarBotones();       // TODO add your handling code here:
    }//GEN-LAST:event_Tabla1FocusGained

    private void btncancel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancel3ActionPerformed
        MP.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btncancel3ActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        // TODO add your handling code here:

        File miDir = new File("");
        String reporte = miDir.getAbsolutePath() + "\\src\\Reportes\\Compra.jasper";

        JasperPrint jp = null;
        try {
            jp = JasperFillManager.fillReport(reporte, null, Conexion.con);
        } catch (JRException ex) {

            //                Logger.getLogger(ProveedorP.class.getName()).log(Level.SEVERE, null, ex);
        }

        JasperViewer view = new JasperViewer(jp, false);
        view.setTitle("Compras - Sistema de Inventario y Facturación RJ");

        view.setZoomRatio((float) 0.70);
        view.setVisible(true);

        view.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        view.toFront();
        //     this.toBack();

        //    this.setExtendedState(javax.swing.JFrame.CROSSHAIR_CURSOR);
    }//GEN-LAST:event_btnprintActionPerformed

    private void btnshowallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowallActionPerformed

        ActualizarTabla();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnshowallActionPerformed

    private void TablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMousePressed

        // TODO add your handling code here:
    }//GEN-LAST:event_TablaMousePressed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked

        if (evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1) {

            int Fila = Tabla.getSelectedRow();

            if (Fila > -1) {

                String ID = (String) Tabla.getValueAt(Fila, 0);
                int ID_Compra = Integer.valueOf(ID);

                BuscarDetalleCompra BuscarDetComp = new BuscarDetalleCompra(this, true);
                BuscarDetComp.setID_Compra(ID_Compra);
                BuscarDetComp.setVisible(true);

            }
            //  Seleccionar();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaMouseClicked

    private void TablaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TablaFocusLost

        // TODO add your handling code here:
    }//GEN-LAST:event_TablaFocusLost

    private void TablaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TablaFocusGained

        // TODO add your handling code here:
    }//GEN-LAST:event_TablaFocusGained

    private void txtbuscKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscKeyReleased
        // Buscar();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscKeyReleased

    public void ActivarBotones(){
        int Fila = Tabla1.getSelectedRow();

            if (Fila > -1) {
               btnpagar.setEnabled(true);
            }
            else{
                btnpagar.setEnabled(false);
            }
    }
    
    public void Pagar(){
      

            int Fila = Tabla1.getSelectedRow();

            if (Fila > -1) {

                String ID = (String) Tabla1.getValueAt(Fila, 0);
                int ID_P = Integer.valueOf(ID);

                try {
                    PagoP PF = new PagoP();
                    PF.setFact(this);
                    PF.setID_Venta(ID_P);
                //    PF.ActualizarTabla();
                    PF.setVisible(true);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(FacturacionP.class.getName()).log(Level.SEVERE, null, ex);
                }
             
       
        
        }
    }
    
   

    public static ResultSet resultado;

    
 
 

  

    public void TituloLista() {
        String header1[] = {"No","Fecha","Cliente", "Total","Vendedor","Cancelada","Estado"};
        ModeloOrdenes.setColumnIdentifiers(header1);

        Tabla1.setModel(ModeloOrdenes);

        JTableHeader header = Tabla1.getTableHeader();
        header.setFont(new Font("Tahoma", Font.BOLD, 14));

  
     
    }

    public void Titulo() {

        String Titu[] = {"No", "Empleado", "Cliente", "Fecha Venta", "Unidads Totales", "Moneda", "Tipo Cambio", "Sub-Total",
            "Descuento", "I.V.A", "Total", "Modo", "Estado"};

        model.setColumnIdentifiers(Titu);

        JTableHeader header = Tabla.getTableHeader();
        header.setFont(new Font("Tahoma", Font.BOLD, 14));

        Tabla.setModel(model);

    }

//    
//    VentasReport DataSourceV = new VentasReport();
//    FacturaReport DataSource = new FacturaReport();
    int vvv = 0;
//ExistenciaReport DataSource2 = new ExistenciaReport();
    int ID_Producto;

 
   
//    ModeloAutoCompletar modelo2 = new ModeloVentasVend();
//    ModeloAutoCompletar modelo3 = new ModeloVentasFechaC();
//     ModeloAutoCompletar modelo1 = new ModeloVentasName();
    public void ActualizarTabla() {

      //  JOptionPane.showMessageDialog(this, "Yeah!");
        TituloLista();

        ModeloOrdenes.setRowCount(0);
        Tabla1.setModel(ModeloOrdenes);

        try {

            resultado = Conexion.consulta("Select * from [dbo].[OrdenFacturarV] where Estado_Venta = "
                    + "'Activo' and Cancelada = 'Pendiente'");

            while (resultado.next()) {

                String[] Datos = new String[7];

                Datos[0] = String.valueOf(resultado.getInt(1));
                
                Date Fecha = resultado.getDate(2);
                SimpleDateFormat format = new SimpleDateFormat("dd 'de' MMMMM 'de' yyyy");

                Datos[1] = format.format(Fecha);
                Datos[2] = resultado.getString(3);
                
                Datos[3] = String.valueOf(resultado.getDouble(4));
                String NombreE = resultado.getString(5);
                String ApellidoE = resultado.getString(6);
                Datos[4] = NombreE.trim() + " " + ApellidoE.trim();
                Datos[5] = resultado.getString(7);
                Datos[6] = resultado.getString(8);
               

                ModeloOrdenes.addRow(Datos);

            }

        } catch (SQLException ex) {
            Logger.getLogger(FacturacionP.class.getName()).log(Level.SEVERE, null, ex);
        }

        Tabla1.setModel(ModeloOrdenes);

    }

    

  
    DefaultTableModel model = new DefaultTableModel() {

        @Override
        public boolean isCellEditable(int row, int column) {
            //all cells false
            return false;
        }
    };

    DefaultTableModel ModeloOrdenes = new DefaultTableModel() {

        Class[] types = new Class[]{
            java.lang.String.class, java.lang.String.class, java.lang.String.class,
            java.lang.String.class, java.lang.String.class, java.lang.String.class,
            java.lang.String.class
        };

        @Override
        public boolean isCellEditable(int row, int column) {

           
                //all cells false
                return false;
            
        }
    };

    

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacturacionP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {

                try {
                    new FacturacionP().setVisible(true);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(FacturacionP.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMnModificar;
    private javax.swing.JPanel PanelVer;
    private javax.swing.JPanel PanelVerFact;
    private org.edisoncor.gui.tabbedPane.TabbedPaneHeader TabbedPane;
    private javax.swing.JTable Tabla;
    private javax.swing.JTable Tabla1;
    private javax.swing.JButton btncancel3;
    private javax.swing.JButton btncancel4;
    private javax.swing.JButton btnpagar;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btnshowall;
    private javax.swing.JButton btnshowall1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cmbbusc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField txtbusc;
    // End of variables declaration//GEN-END:variables
}
