/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Ventanas;

import WebCam.*;
import javax.swing.ImageIcon;

/**
 *
 * @author Reymundo Tenorio
 */
public class ModoImagen extends javax.swing.JDialog {

    /**
     * Creates new form Dispositivos
     * @param parent
     * @param modal
     */
    public ModoImagen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
     
       try {
            this.setIconImage(new ImageIcon(getClass().getResource("Icono.png")).getImage());
        } catch (NullPointerException ex) {
        }
         
        initComponents();
       this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnWebCam = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dispositivo de Captura");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 35, 5));

        btnWebCam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnWebCam.setForeground(new java.awt.Color(255, 255, 255));
        btnWebCam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/WebCam.png"))); // NOI18N
        btnWebCam.setText("Capturar Desde WebCam");
        btnWebCam.setContentAreaFilled(false);
        btnWebCam.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnWebCam.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnWebCam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWebCamActionPerformed(evt);
            }
        });
        jPanel1.add(btnWebCam);

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagen.png"))); // NOI18N
        btnBuscar.setText("Buscar En El Ordenador");
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccionar El Modo Para Obtener La Fotografía");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        setSize(new java.awt.Dimension(650, 286));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   
    private ProductoP Producto;
    private EjecutivoP Ejecutivo;
    private ProveedorP Proveedor;
    private EmpleadoP Empleado;
    private ClienteNaturalP Cliente;
    private ClienteJuridicoP ClienteJ;
    private RepresentanteP Representante;

    public void setBC(BuscarCliente BC) {
        this.BC = BC;
    }
    private BuscarCliente BC;

    public void setRepresentante(RepresentanteP Representante) {
        this.Representante = Representante;
    }
    
    public void setClienteJ(ClienteJuridicoP ClienteJ) {
        this.ClienteJ = ClienteJ;
    }

    public void setProducto(ProductoP Producto) {
        this.Producto = Producto;
    }

    public void setEjecutivo(EjecutivoP Ejecutivo) {
        this.Ejecutivo = Ejecutivo;
    }

    public void setProveedor(ProveedorP Proveedor) {
        this.Proveedor = Proveedor;
    }

    public void setEmpleado(EmpleadoP Empleado) {
        this.Empleado = Empleado;
    }

    public void setCliente(ClienteNaturalP Cliente) {
        this.Cliente = Cliente;
    }
    

  
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

      this.setResizable(false);
      this.toFront();
   
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened
 
  
 private boolean Flag = false;
 
    private void btnWebCamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWebCamActionPerformed

         if(Representante!=null){
              this.Flag = true;
              Dispositivos Pic = new Dispositivos(null, false);
              Pic.setRepresentante(Representante);
              Pic.setVisible(true);   
              this.dispose();
        }
          if(BC!=null){
              this.Flag = true;
              Dispositivos Pic = new Dispositivos(null, false);
              Pic.setBC(BC);
              Pic.setVisible(true);   
              this.dispose();
        }
       
         if(Cliente!=null){
              this.Flag = true;
              Dispositivos Pic = new Dispositivos(Cliente, false);
              Pic.setCliente(Cliente);
              Pic.setVisible(true);   
              this.dispose();
        }
         
          if(ClienteJ!=null){
              this.Flag = true;
              Dispositivos Pic = new Dispositivos(ClienteJ, false);
              Pic.setClienteJ(ClienteJ);
              Pic.setVisible(true);   
              this.dispose();
        }
         
          if(Proveedor!=null){
              this.Flag = true;
              Dispositivos Pic = new Dispositivos(Proveedor, false);
              Pic.setProveedor(Proveedor);
              Pic.setVisible(true);   
              this.dispose();
        }
          
           if(Ejecutivo!=null){
              this.Flag = true;
              Dispositivos Pic = new Dispositivos(Ejecutivo, false);
              Pic.setEjecutivo(Ejecutivo);
              Pic.setVisible(true);   
              this.dispose();
        }
           
            if(Producto!=null){
              this.Flag = true;
              Dispositivos Pic = new Dispositivos(Producto, false);
              Pic.setProducto(Producto);
              Pic.setVisible(true);   
              this.dispose();
        }
             if(Empleado!=null){
              this.Flag = true;
              Dispositivos Pic = new Dispositivos(Empleado, false);
              Pic.setEmpleado(Empleado);
              Pic.setVisible(true);   
              this.dispose();
        }
            
        
        
                   
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnWebCamActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        
         if(Representante!=null){   
        this.Flag = true;
        Representante.AddPic();
        Representante.setVisible(true);
        this.dispose();  
        }
          if(BC!=null){   
        this.Flag = true;
        BC.AddPic();
        BC.setVisible(true);
        this.dispose();  
        }
     
        if(Cliente!=null){   
        this.Flag = true;
        Cliente.AddPic();
        Cliente.setVisible(true);
        this.dispose();  
        }
        
         if(ClienteJ!=null){   
        this.Flag = true;
        ClienteJ.AddPic();
        ClienteJ.setVisible(true);
        this.dispose();  
        }
        
        if(Proveedor!=null){   
        this.Flag = true;
        Proveedor.AddPic();
        Proveedor.setVisible(true);
        this.dispose();  
        }
        
        if(Ejecutivo!=null){   
        this.Flag = true;
        Ejecutivo.AddPic();
        Ejecutivo.setVisible(true);
        this.dispose();  
        }
        
        if(Producto!=null){   
        this.Flag = true;
        Producto.AddPic();
        Producto.setVisible(true);
        this.dispose();  
        }
        
        if(Empleado!=null){   
        this.Flag = true;
        Empleado.AddPic();
        Empleado.setVisible(true);
        this.dispose();  
        }
       
                   
              // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
   
        if(Flag == false){
            
        if(Representante!=null){
        Representante.setVisible(true);
        }
        if(BC!=null){
        BC.setVisible(true);
        }
        if(Empleado!=null){         
        Empleado.setVisible(true);
        }
        if(Cliente!=null){
        Cliente.setVisible(true);
        }
         if(ClienteJ!=null){
        ClienteJ.setVisible(true);
        }
        if(Proveedor!=null){
        Proveedor.setVisible(true);
        }
        if(Ejecutivo!=null){
        Ejecutivo.setVisible(true);
        }
        if(Producto!=null){
        Producto.setVisible(true);
        }
       
        }   // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModoImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ModoImagen dialog = new ModoImagen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnWebCam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
