/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Ventanas;

import WebCam.*;
import javax.swing.ImageIcon;

/**
 *
 * @author Reymundo Tenorio
 */
public class ModoCliente extends javax.swing.JDialog {

    /**
     * Creates new form Dispositivos
     * @param parent
     * @param modal
     */
    public ModoCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
     
        try {
            this.setIconImage(new ImageIcon(getClass().getResource("Icono.png")).getImage());
        } catch (NullPointerException ex) {
        }
         
        initComponents();
       this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnClienteNatural = new javax.swing.JButton();
        btnClienteJuridico = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tipo de Cliente");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 35, 5));

        btnClienteNatural.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClienteNatural.setForeground(new java.awt.Color(255, 255, 255));
        btnClienteNatural.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ClienteNatural.png"))); // NOI18N
        btnClienteNatural.setMnemonic('N');
        btnClienteNatural.setText("Cliente Natural");
        btnClienteNatural.setContentAreaFilled(false);
        btnClienteNatural.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClienteNatural.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClienteNatural.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteNaturalActionPerformed(evt);
            }
        });
        jPanel1.add(btnClienteNatural);

        btnClienteJuridico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClienteJuridico.setForeground(new java.awt.Color(255, 255, 255));
        btnClienteJuridico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ClienteJuridico.png"))); // NOI18N
        btnClienteJuridico.setMnemonic('J');
        btnClienteJuridico.setText("Cliente Jurídico");
        btnClienteJuridico.setContentAreaFilled(false);
        btnClienteJuridico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClienteJuridico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClienteJuridico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteJuridicoActionPerformed(evt);
            }
        });
        jPanel1.add(btnClienteJuridico);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccionar Tipo de Cliente");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        setSize(new java.awt.Dimension(650, 243));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

      this.setResizable(false);
      this.toFront();
   
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened
 
    MenuPrincipal MP;

    public void setMP(MenuPrincipal MP) {
        this.MP = MP;
    }
  
 private boolean Flag = false;
 
 
 boolean Cerrar;
 
    private void btnClienteNaturalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteNaturalActionPerformed

      ClienteNaturalP CP = new ClienteNaturalP();
      CP.setMP(this.MP);
      CP.setVisible(true);

      Cerrar = true;
      
      this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_btnClienteNaturalActionPerformed

    private void btnClienteJuridicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteJuridicoActionPerformed

      ClienteJuridicoP CP = new ClienteJuridicoP();
      CP.setMP(this.MP);
      CP.setVisible(true);

      Cerrar = true;
      
      this.dispose();
                   
              // TODO add your handling code here:
    }//GEN-LAST:event_btnClienteJuridicoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
   
        if(Cerrar == false){
            
            this.MP.setVisible(true);
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ModoCliente dialog = new ModoCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClienteJuridico;
    private javax.swing.JButton btnClienteNatural;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
