/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.FacturaTablaPJ;
import Clases.FacturacionPJ;
import Procedimientos.Conexion;
import Procedimientos.Orden;
import Reportes.FacturaReport;
import ServerSocket.ClienteServer;
import com.keffect.effects.animatedEffects.EntryBoucing;
import com.keffectpanel.KEffectPanel;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.net.UnknownHostException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Reymundo Tenorio
 */
public class PagoP extends javax.swing.JFrame {

    /**
     * Creates new form ProductoP
     */
    public PagoP() throws UnknownHostException {

       try {
            this.setIconImage(new ImageIcon(getClass().getResource("Icono.png")).getImage());
        } catch (NullPointerException ex) {
        }
         

        initComponents();
        JTableLista.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
  
   

        /*COPIAR PEGAR DESACTIVAR*/
//         JTextComponent.KeyBinding[] newBindings = {
////        new JTextComponent.KeyBinding(
////          KeyStroke.getKeyStroke(KeyEvent.VK_C, InputEvent.CTRL_MASK),
////          DefaultEditorKit.beepAction),
//        new JTextComponent.KeyBinding(
//          KeyStroke.getKeyStroke(KeyEvent.VK_V, InputEvent.CTRL_MASK),
//          DefaultEditorKit.beepAction),
////        new JTextComponent.KeyBinding(
////            KeyStroke.getKeyStroke(KeyEvent.VK_X, InputEvent.CTRL_MASK),
////            DefaultEditorKit.beepAction)
////      
//         };
//            
//    Keymap k = txtNombre.getKeymap();
//    JTextComponent.loadKeymap(k, newBindings, txtNombre.getActions());
//    
//        MultipleEffect effects = new MultipleEffect();
//				effects.addEffect(new ShadowFrame(20));
//				effects.addEffect(new Shadow(1000));
//				effects.addEffect(new SplitHorizontalFade(1000));
//				effects.addEffect(new SplitVerticalFade(2000));
//				effects.addEffect(new DarkenReverse(6000,50));
//                                
        // PanelEffect.setEffect(effects);                    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        JMnModificar = new javax.swing.JMenuItem();
        TabbedPane = new org.edisoncor.gui.tabbedPane.TabbedPaneHeader();
        PanelNuevo = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtCambio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jFecha = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        txtCajero = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        txtCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtVendedor = new javax.swing.JTextField();
        lblMoneda = new javax.swing.JLabel();
        cmbMoneda = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        rdEfectivo = new javax.swing.JRadioButton();
        rdTarjeta = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        JTableLista = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtIVA = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cmbDescuento = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        btnProcesar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnCancelar1 = new javax.swing.JButton();

        JMnModificar.setText("Modificar");
        JMnModificar.setToolTipText("Modificar");
        jPopupMenu1.add(JMnModificar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pago Factura");
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        TabbedPane.setPreferredSize(new java.awt.Dimension(200, 574));

        //KEffectPanel effectPanel = new KEffectPanel();
        //PanelNuevo = effectPanel;
        PanelNuevo = PanelEffect;
        PanelNuevo.setBackground(new java.awt.Color(0, 153, 204));
        PanelNuevo.setLayout(new javax.swing.BoxLayout(PanelNuevo, javax.swing.BoxLayout.LINE_AXIS));

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel16.setOpaque(false);
        jPanel16.setLayout(new javax.swing.BoxLayout(jPanel16, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información de Factura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel14.setOpaque(false);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Tipo de Cambio");

        txtCambio.setEditable(false);
        txtCambio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCambio.setForeground(new java.awt.Color(0, 51, 51));
        txtCambio.setToolTipText("Tipo de Cambio Actual del Dólar");
        txtCambio.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Fecha");

        jFecha.setDateFormatString("dd-MM-yyyy");
        jFecha.setEnabled(false);
        jFecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jFecha.getDateEditor().getUiComponent().addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jdFechaKeyTyped(evt);
            }
        });

        jFecha.getDateEditor().getUiComponent().addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jdFechaKeyReleased(evt);
            }
        });

        jFecha.getDateEditor().getUiComponent().addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jdFechaKeyPressed(evt);
            }
        });

        jFecha.getDateEditor().getUiComponent().setToolTipText("Seleccione Fecha");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cajero");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        txtCajero.setEditable(false);
        txtCajero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCajero.setForeground(new java.awt.Color(0, 51, 51));
        txtCajero.setToolTipText("Tipo de Cambio Actual del Dólar");
        txtCajero.setEnabled(false);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
        );

        jPanel16.add(jPanel14);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información Adicional", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel11.setOpaque(false);

        txtCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCliente.setToolTipText("Ingrese el Nombre del Cliente");
        txtCliente.setEnabled(false);
        txtCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClienteKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cliente");

        txtVendedor.setEditable(false);
        txtVendedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtVendedor.setForeground(new java.awt.Color(0, 51, 51));
        txtVendedor.setToolTipText("Nombre del Vendedor");
        txtVendedor.setEnabled(false);

        lblMoneda.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblMoneda.setForeground(new java.awt.Color(255, 255, 255));
        lblMoneda.setText("Tipo de Moneda");

        cmbMoneda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbMoneda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Córdobas", "Dólares" }));
        cmbMoneda.setToolTipText("Seleccione El Tipo de Moneda");
        cmbMoneda.setName(""); // NOI18N
        cmbMoneda.setPreferredSize(new java.awt.Dimension(220, 23));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tipo de Pago");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jPanel13.setOpaque(false);

        buttonGroup1.add(rdEfectivo);
        rdEfectivo.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        rdEfectivo.setForeground(new java.awt.Color(255, 255, 255));
        rdEfectivo.setSelected(true);
        rdEfectivo.setText("Efectivo");
        rdEfectivo.setToolTipText("Seleccione Si El Pago Es En Efectivo");
        rdEfectivo.setOpaque(false);
        jPanel13.add(rdEfectivo);

        buttonGroup1.add(rdTarjeta);
        rdTarjeta.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        rdTarjeta.setForeground(new java.awt.Color(255, 255, 255));
        rdTarjeta.setText("Tarjeta");
        rdTarjeta.setToolTipText("Seleccione Si El Pago Es Con Tarjeta de Crédito");
        rdTarjeta.setOpaque(false);
        rdTarjeta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdTarjetaItemStateChanged(evt);
            }
        });
        jPanel13.add(rdTarjeta);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Vendedor");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMoneda, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(152, 152, 152)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                    .addContainerGap(622, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(326, 326, 326)))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(36, Short.MAX_VALUE)))
        );

        jPanel16.add(jPanel11);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel10.setOpaque(false);
        jPanel10.setLayout(new java.awt.BorderLayout());

        JTableLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        JTableLista.setToolTipText("Lista de Productos a Facturar");
        JTableLista.setComponentPopupMenu(jPopupMenu1);
        JTableLista.setEnabled(false);
        JTableLista.getTableHeader().setReorderingAllowed(false);
        JTableLista.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTableListaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTableListaFocusLost(evt);
            }
        });
        JTableLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableListaMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(JTableLista);

        jPanel10.add(jScrollPane6, java.awt.BorderLayout.CENTER);

        jPanel16.add(jPanel10);

        PanelNuevo.add(jPanel16);

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(255, 255, 255))); // NOI18N

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información de Pago", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.GridLayout(4, 2, 5, 5));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("  Sub-Total");
        jPanel8.add(jLabel16);

        txtSubTotal.setEditable(false);
        txtSubTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSubTotal.setToolTipText("Sub-Total de La Venta");
        jPanel8.add(txtSubTotal);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("  I.V.A.");
        jPanel8.add(jLabel19);

        txtIVA.setEditable(false);
        txtIVA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtIVA.setToolTipText("Total a Pagar");
        jPanel8.add(txtIVA);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("  Descuento");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel8.add(jLabel17);

        cmbDescuento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbDescuento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0%", "5%", "10%" }));
        cmbDescuento.setToolTipText("Porcentaje de Descuento");
        cmbDescuento.setEnabled(false);
        cmbDescuento.setMaximumSize(new java.awt.Dimension(121, 23));
        cmbDescuento.setName(""); // NOI18N
        cmbDescuento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDescuentoItemStateChanged(evt);
            }
        });
        jPanel8.add(cmbDescuento);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("  TOTAL A PAGAR");
        jPanel8.add(jLabel18);

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotal.setToolTipText("Total a Pagar");
        jPanel8.add(txtTotal);

        jPanel9.setBackground(new java.awt.Color(0, 102, 153));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel9.setOpaque(false);

        btnProcesar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnProcesar.setForeground(new java.awt.Color(255, 255, 255));
        btnProcesar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fact.png"))); // NOI18N
        btnProcesar.setMnemonic('p');
        btnProcesar.setText("Facturar");
        btnProcesar.setToolTipText("Procesar y Facturar Orden");
        btnProcesar.setContentAreaFilled(false);
        btnProcesar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProcesar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/No.png"))); // NOI18N
        btnCancelar.setMnemonic('c');
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Cancelar / Salir");
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnCancelar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar1.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Calculadora.png"))); // NOI18N
        btnCancelar1.setMnemonic('A');
        btnCancelar1.setText("Calculadora");
        btnCancelar1.setToolTipText("Abrir Calculadora");
        btnCancelar1.setContentAreaFilled(false);
        btnCancelar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelNuevo.add(jPanel2);

        TabbedPane.addTab("Nuevo", PanelNuevo);

        getContentPane().add(TabbedPane, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1308, 742));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    KEffectPanel PanelEffect = new KEffectPanel();
    KEffectPanel PanelEffect2 = new KEffectPanel();

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//                this.panelColor = new JPanel();
//		this.panelColor.setBackground(Color.BLACK);
//		this.panelColor.setBorder(new LineBorder(new Color(0, 0, 0)));
//		this.panelColor.setBounds(133, 618, 43, 32);
//                
//     PanelEffect.setEffect(new SplitHorizontalFade (1000,panelColor.getBackground()));
//     PanelEffect.startEffect();

        PanelEffect.setEffect(new EntryBoucing(1000));
        PanelEffect.startEffect();

//Date now = new Date();
//
//DateFormat df =  DateFormat.getDateInstance();
//DateFormat df1 = DateFormat.getDateInstance(DateFormat.SHORT);
//DateFormat df2 = DateFormat.getDateInstance(DateFormat.MEDIUM);
//DateFormat df3 = DateFormat.getDateInstance(DateFormat.LONG);
//DateFormat df4 = DateFormat.getDateInstance(DateFormat.FULL);
//String s =  df.format(now);
//String s1 = df1.format(now);
//String s2 = df2.format(now);
//String s3 = df3.format(now);
//String s4 = df4.format(now);
//System.out.println("(Default) Hoy es:" + s);
//System.out.println("(SHORT)   Hoy es:" + s1);
//System.out.println("(MEDIUM)  Hoy es:" + s2);
//System.out.println("(LONG)    Hoy es:" + s3);
//System.out.println("(FULL)    Hoy es:" + s4);
        double Cambio = 0;
        int ID_Cambio = 0;
        String Empleado = "";

        try {
            resultado = Conexion.consulta("Select  Nombres_Empleado, Apellidos_Empleado "
                    + "from Empleado where ID_Empleado = " + MenuPrincipal.ID_Usuario);
            while (resultado.next()) {
                Empleado = resultado.getString(1).trim() + " " + resultado.getString(2).trim();
            }

            txtCajero.setText(Empleado);

        } catch (SQLException ex) {
        }

        int ID_TipoCambio = 0;

           try{
               resultado = Conexion.consulta("Select Max(ID_Tipo_Cambio) from [dbo].[Tipo_Cambio]");
               
               while(resultado.next()){
               ID_TipoCambio = resultado.getInt(1);
               }
           }catch(SQLException ex){}
           
           try{

            resultado = Conexion.consulta("Select Tipo_Cambio from Tipo_Cambio");// where ID_Tipo_Cambio = " + ID_Cambio);
            while (resultado.next()) {
                Cambio = resultado.getDouble(1);
            }
        } catch (SQLException ex) {
        }

        txtCambio.setText(String.valueOf(Cambio));

//        try {
//            txtCambio.setText(new ObtenerCambio().Cambio());
//        } catch (IOException ex) { }
       
      
        ModeloProductos.setNumRows(0);

        TituloLista();

       ActualizarTabla();
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    public void jdFechaKeyTyped(KeyEvent evt) {

        char a = evt.getKeyChar();

        evt.consume();
        Toolkit.getDefaultToolkit().beep();

    }

    public void jdFechaKeyPressed(KeyEvent evt) {
        char a = evt.getKeyChar();

        evt.consume();
        Toolkit.getDefaultToolkit().beep();

    }

    public void jdFechaKeyReleased(KeyEvent evt) {
        char a = evt.getKeyChar();

        evt.consume();
        Toolkit.getDefaultToolkit().beep();

    }


    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed


    private void txtClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteKeyTyped

 
    private void JTableListaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTableListaFocusLost

        // TODO add your handling code here:
    }//GEN-LAST:event_JTableListaFocusLost

    private void JTableListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableListaMouseClicked

    

        // TODO add your handling code here:
    }//GEN-LAST:event_JTableListaMouseClicked

    private void cmbDescuentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDescuentoItemStateChanged

// TODO add your handling code here:
    }//GEN-LAST:event_cmbDescuentoItemStateChanged
FacturacionP Fact;

    public void setFact(FacturacionP Fact) {
        this.Fact = Fact;
    }


    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed


        Procesar();
 
        ModeloProductos.setNumRows(0);
        JTableLista.setModel(ModeloProductos);
        
        TituloLista();
        Fact.ActualizarTabla();
        dispose();
       
// TODO add your handling code here:
    }//GEN-LAST:event_btnProcesarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        AbrirCalculadora();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private void rdTarjetaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdTarjetaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rdTarjetaItemStateChanged

    private void JTableListaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTableListaFocusGained
  // TODO add your handling code here:
    }//GEN-LAST:event_JTableListaFocusGained

    public void AbrirCalculadora() {

        String Comando = "calc.exe"; //"cmd /C dir"
        try {
          /*  Process p = */Runtime.getRuntime().exec(Comando);
//            BufferedReader in = new BufferedReader(
//                    new InputStreamReader(p.getInputStream()));
//            String line = "";
//            while ((line = in.readLine()) != null) {
//                System.out.println(line);
//            }
        } catch (IOException e) {
        }

    }

    public static ResultSet resultado;

 

    public void TituloLista() {
        String header1[] = {"", "Unidades", "Descripción del Producto", "Precio de Venta", "Total","Individual"};
        ModeloProductos.setColumnIdentifiers(header1);

        JTableLista.setModel(ModeloProductos);

        JTableHeader header = JTableLista.getTableHeader();
        header.setFont(new Font("Tahoma", Font.BOLD, 14));

  
    }


//    
//    VentasReport DataSourceV = new VentasReport();
//    FacturaReport DataSource = new FacturaReport();
    int vvv = 0;
//ExistenciaReport DataSource2 = new ExistenciaReport();


   

//    ModeloAutoCompletar modelo2 = new ModeloVentasVend();
//    ModeloAutoCompletar modelo3 = new ModeloVentasFechaC();
//     ModeloAutoCompletar modelo1 = new ModeloVentasName();
    
    int ID_Venta = 0;

    public void setID_Venta(int ID_Venta) {
        this.ID_Venta = ID_Venta;
    }
    
    String TipoFactura;
    
    
    public void ActualizarTabla() {

        TituloLista();

        ModeloProductos.setRowCount(0);
        JTableLista.setModel(ModeloProductos);

        String Cliente= "";
        String Cajero = "";
        String Vendedor= "";
        String Descuento= "";
        double Subtotal =0;
        double IVA=0;
        double Total=0;
        Date Fecha = null;
        
         try {

            resultado = Conexion.consulta("Select * from FacturarV where ID_Venta = "+ID_Venta);

            while (resultado.next()) {

           resultado.getInt(1);
           
           Fecha = resultado.getDate(2);
           Cliente = resultado.getString(3);
           Vendedor = resultado.getString(4).trim()+" "+resultado.getString(5).trim();
           Subtotal = resultado.getDouble(6);
           IVA = resultado.getDouble(7);
           Descuento = resultado.getString(8);
           Total= resultado.getDouble(9);
           resultado.getString(10);

            }

        } catch (SQLException ex) {
            Logger.getLogger(PagoP.class.getName()).log(Level.SEVERE, null, ex);
        }
         
           try {

            resultado = Conexion.consulta("Select [Tipo_Factura] from [dbo].[Venta] where ID_Venta = "+ID_Venta);

            while (resultado.next()) {
               
               TipoFactura = resultado.getString(1);

            }

        } catch (SQLException ex) {
            Logger.getLogger(PagoP.class.getName()).log(Level.SEVERE, null, ex);
        }
         
         
         try {

            resultado = Conexion.consulta("Select [Nombres_Empleado], [Apellidos_Empleado]"
                    + " from Empleado where ID_Empleado = "+MenuPrincipal.ID_Usuario);

            while (resultado.next()) {

            Cajero = resultado.getString(1).trim()+" "+resultado.getString(2).trim();
            }

        } catch (SQLException ex) {
            Logger.getLogger(PagoP.class.getName()).log(Level.SEVERE, null, ex);
        }

         txtCajero.setText(Cajero);
         txtVendedor.setText(Vendedor);
         txtCliente.setText(Cliente);
         txtIVA.setText(String.valueOf(IVA));
         txtSubTotal.setText(String.valueOf(Subtotal));
         txtTotal.setText(String.valueOf(Total));
         cmbDescuento.setSelectedItem(Descuento);
         jFecha.setDate(Fecha);
         
        
        try {

            resultado = Conexion.consulta("Select * from DetallesOrden where ID_Venta = "+ID_Venta);

            while (resultado.next()) {

                Object [] Datos = new Object[6];

                Datos[0] = "";
                resultado.getInt(1);
                resultado.getInt(2);
                Datos[1] = String.valueOf(resultado.getInt(3));
                Datos[2] = resultado.getString(4);
                Datos[3] = String.valueOf(resultado.getDouble(5));
                Datos[4] = String.valueOf(resultado.getDouble(6));
                Datos[5] = resultado.getString(7);
         
                ModeloProductos.addRow(Datos);

            }

        } catch (SQLException ex) {
            Logger.getLogger(PagoP.class.getName()).log(Level.SEVERE, null, ex);
        }

        JTableLista.setModel(ModeloProductos);

    }
    
    double DineroRecibido = 0;

    public void setRecibido(double Recibido) {
        this.DineroRecibido = Recibido;
    }
    

    public void Procesar() {
        vvv = 0;
        FacturaReport DataSource = new FacturaReport();

        String NombreCliente = "";
        String Vendedor;
        String TipoMoneda;
        String TipoPago;
        String ModoFactura;
        String Total;
        String SubTotal;
        String Descuento;
        String IVA;
       
         ModoFactura = TipoFactura.trim();
         
            if (rdEfectivo.isSelected()) {
            TipoPago = "Efectivo";
        } else {
            TipoPago = "Tarjeta";
        }
            
            if("Crédito".equals(ModoFactura)){
                TipoPago = "Crédito";
            }
  

         NombreCliente = txtCliente.getText().trim();
     

            Vendedor = txtVendedor.getText();
            TipoMoneda = (String) cmbMoneda.getSelectedItem();
           
            double Total1, SubTotal1, IVA1;
            Total = txtTotal.getText().trim();
            Total1 = Double.parseDouble(Total);
            SubTotal = txtSubTotal.getText().trim();
            SubTotal1 = Double.parseDouble(SubTotal);
            IVA = txtIVA.getText().trim();
            IVA1 = Double.parseDouble(IVA);
            
            Descuento = (String) cmbDescuento.getSelectedItem();

    
            double TipoC = Double.parseDouble(txtCambio.getText().trim());
           
            
       
           int ID_P = ID_Venta;
           
          
           

            FacturacionPJ fc = new FacturacionPJ();

            fc.setNombreCliente(NombreCliente);
            fc.setID(ID_P);
            fc.setDescuento(Descuento);
            fc.setSubTotal(SubTotal1);
            fc.setTipoMoneda(TipoMoneda);
            fc.setTipoPago(TipoPago);
            fc.setTotal(Total1);
            fc.setVendedor(Vendedor);
            fc.setIVA(IVA1);
            fc.setTipoFactura(ModoFactura);
            fc.setCajero(Vendedor);

            int c1 = JTableLista.getRowCount();

            for (int k = 0; k < c1; k++) {

                FacturaTablaPJ fc1 = new FacturaTablaPJ();

                String Unids1 = this.JTableLista.getModel().getValueAt(k, 1).toString();
                String NombreProducto1 = this.JTableLista.getModel().getValueAt(k, 2).toString();
                String PV1 = this.JTableLista.getModel().getValueAt(k, 3).toString();
                String TotalF1 = this.JTableLista.getModel().getValueAt(k, 4).toString();
                String Indiv= this.JTableLista.getModel().getValueAt(k, 5).toString();
                
                if("Individual".equals(Indiv)){
                    NombreProducto1 = "#"+NombreProducto1;
                }
                
                fc1.setUnids(Unids1);
                fc1.setNombreProducto(NombreProducto1);
                fc1.setPV(PV1);
                fc1.setTotalF(TotalF1);

                DataSource.addValor1(fc1);
            }

            double recibido = 0;
            double cambio = 0;
            
             if(!"Crédito".equals(ModoFactura)){
            DineroRecibido DR = new DineroRecibido(this, true);
            if("Córdobas".equals(TipoMoneda)){
            DR.AgregarTexto("Ingrese La Cantidad de Córdobas Recibidos");
            }
            if("Dólares".equals(TipoMoneda)){
            DR.AgregarTexto("Ingrese La Cantidad de Dólares Recibidos");
            }
            DR.setMoneda(TipoMoneda);
            DR.setTipo(TipoC);
            DR.setPago(Total1);
            DR.setFc(this);
            DR.setVisible(true);
            
        
            recibido = DineroRecibido;
            
            double Cam = DineroRecibido-Total1;
            
            Cambio Change = new Cambio(this, true);
            DecimalFormat df = new DecimalFormat("#0.00");
            String Camb = df.format(Cam).replace(',','.');
            Change.AgregarTexto(Camb);
            Change.setVisible(true);           
            cambio = Double.parseDouble(Camb);
             }
            Orden.Pagar_Orden(ID_Venta, TipoMoneda, ModoFactura, recibido);
            
            fc.setTipoCambio(TipoC);
            fc.setCambio(cambio);
            fc.setRecibido(recibido);

            DataSource.addValor(fc);

            
            File F = new File("");
            String RutaFarmacia = F.getAbsolutePath() + "\\Facturas\\";
            File Farmacia = new File(RutaFarmacia);

            if (!Farmacia.exists()) {
                Farmacia.mkdir();
            }

            String reporte = F.getAbsolutePath() + "\\src\\Reportes\\Factura.jasper";

            JasperPrint jp = null;
            try {
                jp = JasperFillManager.fillReport(reporte, null, DataSource);
                JasperExportManager.exportReportToPdfFile(jp, F.getAbsolutePath() + "\\Facturas\\Factura_" + ID_P + ".pdf");

            } catch (JRException ex) {

            }
            JasperViewer view = new JasperViewer(jp, false);

            view.setTitle("Factura");
            
        view.setZoomRatio((float) 0.70);
        view.setVisible(true);

        view.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        view.toFront();

        
    }


    DefaultTableModel ModeloProductos = new DefaultTableModel() {

        Class[] types = new Class[]{
            java.lang.Boolean.class, java.lang.String.class, java.lang.String.class,
            java.lang.String.class, java.lang.String.class, 
            java.lang.String.class
        };

        @Override
        public boolean isCellEditable(int row, int column) {

           
                //all cells false
                return false;
            
        }
    };

 
     class ClienteServerInit extends Thread{

     ClienteServer ServerC = new ClienteServer();

@Override
public void run(){
       
    
         try {
             ServerC.IniciarConexion();
         } catch (IOException ex) {
             Logger.getLogger(PagoP.class.getName()).log(Level.SEVERE, null, ex);
         }
   
}
    }
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagoP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {

                try {
                    new PagoP().setVisible(true);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(PagoP.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMnModificar;
    private javax.swing.JTable JTableLista;
    private javax.swing.JPanel PanelNuevo;
    private org.edisoncor.gui.tabbedPane.TabbedPaneHeader TabbedPane;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnProcesar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cmbDescuento;
    private javax.swing.JComboBox cmbMoneda;
    private com.toedter.calendar.JDateChooser jFecha;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblMoneda;
    private javax.swing.JRadioButton rdEfectivo;
    private javax.swing.JRadioButton rdTarjeta;
    private javax.swing.JTextField txtCajero;
    private javax.swing.JTextField txtCambio;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtIVA;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtVendedor;
    // End of variables declaration//GEN-END:variables
}
